INSERT INTO TBLDATA_KEN
SELECT '20101101' As  TXDATE, CUSTID, PKGCODE, 
   PKGSEQNO, DEVCODE, DEVID, 
   STIME, MNTSE15, TXTIME, 
   V1, V2, V3, 
   V12, V23, V31, 
   A1, A2, A3, 
   VTOT, VARTOT, WTOT, 
   VATOT, ATOT, PFTOT, 
   HZTOT, LOAD, DEVDATE, 
   DEVTIME, IMPKWH, EXPKVARH, 
   VA1, VA2, VA3, 
   W1, W2, W3, 
   VAR1, VAR2, VAR3, 
   PF1, PF2, PF3, 
   CF1, CF2, CF3, 
   FV12, FV23, FV31, 
   FA1, FA2, FA3, 
   SUBDATE, SUBTIME, SUBKWH, 
   PLUSE, SYNCTIME, DEMCURR, 
   DEMLAST, DEMMAX, TEMPTR, 
   TEMPPAN, DEMTARGET, DEMPRE, 
   UNTOT, CURRENERG, VTHD1, 
   VTHD2, VTHD3, ATHD1, 
   ATHD2, ATHD3, TRTOTKWH, 
   SUM_RESET_DATE, SUM_RESET_TIME, DEM_RESET_DATE, 
   DEM_RESET_TIME, ELD, EXPKWH, 
   IMPKVARH
FROM TBLDATA_KEN
WHERE CUSTID = 'kdpower'
AND TXDATE = '20101001'
COMMIT